https://official.contest.yandex.ru/contest/44416/run-report/81538812/
brezhart/hashmap pull request #1
Opened 2023-03-05 16:48 UTC by brezhart

https://official.contest.yandex.ru/contest/44416/run-report/81538812/

2023-06-13 20:35 UTC, lioshik requested changes

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +#include "bits/stdc++.h"
вот это хуйня ебаная раздувает время компиляции, у тебя теперь в этом файле будет своя собственная копия всего stl

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +        Node* last = nullptr;
вот это вот древняя хуета, надо на умные указатели переписать иначе утечки будут и хуй потом разберешь где че утекло

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +        Node(HashMap* mp, const KV& key_value , size_t bucket_index = 0): bucket_index(bucket_index), key_value(key_value){
полное говно, тут пробел перед запятой, это проверку линтером не пройдет

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +        iterator(const Node& node): node(&node){
правило пяти для ебанатов что ли придумали? на пересдачу

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +        }
правило пяти в этом итераторе идет нахуй

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +    HashMap(const HashMap&rhs){
желаю автору shift+shift + format code в силайоне

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +};
ВЕРДИКТ: 
переписать на раст

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +    int get_psl(int index){
название функции супер хуевое

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +    int get_psl(int index){
индекс тогда уж size_t

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +            return *this;
база

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +    HashMap(const HashMap&rhs){
а лучше vs code с линтером

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +        for (auto el: init_list){
а че бы и не const auto& вместо auto

2023-06-13 20:35 UTC, lioshik commented on hashmap_branch.h
> +        hasher_ = Hash();
где мув конструктор и мув оператор присваивания? 0 rps

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +#include "bits/stdc++.h"
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +        Node* last = nullptr;
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +        Node(HashMap* mp, const KV& key_value , size_t bucket_index = 0): bucket_index(bucket_index), key_value(key_value){
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +    int get_psl(int index){
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +        iterator(const Node& node): node(&node){
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +        }
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +        hasher_ = Hash();
Согласен с Алексеем

2023-06-13 20:35 UTC, Anuiel commented on hashmap_branch.h
> +    HashMap(const HashMap&rhs){
Согласен с Алексеем

2023-06-13 20:36 UTC, Anuiel commented on hashmap_branch.h
> +        for (auto el: init_list){
Согласен с Алексеем

2023-06-13 20:36 UTC, Anuiel commented on hashmap_branch.h
> +            return *this;
Согласен с Алексеем

2023-06-13 20:36 UTC, Anuiel commented on hashmap_branch.h
> +};
Раст лучший язык программирования

2023-06-13 20:36 UTC, Anuiel commented
Алексей Смирнов навалил базы

2023-06-13 20:38 UTC, lioshik commented
Артем Брежнев 0 на сопе, я отзываю свой рефер

2023-06-13 20:41 UTC, brezhart commented on hashmap_branch.h
> +        hasher_ = Hash();
я мув в твой рот делал не пиши сюда 😡😡😡😡

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +#include "bits/stdc++.h"
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +        Node* last = nullptr;
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +        Node(HashMap* mp, const KV& key_value , size_t bucket_index = 0): bucket_index(bucket_index), key_value(key_value){
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +        iterator(const Node& node): node(&node){
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +        }
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +    HashMap(const HashMap&rhs){
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +};
Согласен с Максимом

2023-06-13 21:03 UTC, h0tmi commented on hashmap_branch.h
> +    int get_psl(int index){
Согласен с Максимом

2023-06-13 21:04 UTC, h0tmi commented on hashmap_branch.h
> +            return *this;
Согласен с Максимом

2023-06-13 21:04 UTC, h0tmi commented on hashmap_branch.h
> +        for (auto el: init_list){
Согласен с Максимом

2023-06-13 21:04 UTC, h0tmi commented on hashmap_branch.h
> +        hasher_ = Hash();
Согласен с Максимом

2023-06-14 11:08 UTC, merged

2023-06-14 11:08 UTC, ooorlov commented on hashmap_branch.h
> +        }
Согласен с Тимофеем

2023-06-14 11:08 UTC, ooorlov commented on hashmap_branch.h
> +};
Согласен с Тимофеем

2023-06-14 11:08 UTC, ooorlov commented on hashmap_branch.h
> +    int get_psl(int index){
Согласен с Тимофеем

2023-06-14 11:08 UTC, ooorlov commented on hashmap_branch.h
> +            return *this;
Согласен с Тимофеем

2023-06-14 11:08 UTC, ooorlov commented on hashmap_branch.h
> +        for (auto el: init_list){
Согласен с Тимофеем

2023-06-14 11:08 UTC, ooorlov commented on hashmap_branch.h
> +        hasher_ = Hash();
Согласен с Тимофеем